# Generated by Django 5.0.1 on 2026-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Meeting date')),
                ('start_time', models.TimeField(help_text='Meeting start time')),
                ('end_time', models.TimeField(help_text='Meeting end time')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone of the booking', max_length=50)),
                ('meeting_purpose', models.TextField(help_text='Purpose or agenda of the meeting')),
                ('meeting_link', models.URLField(blank=True, help_text='Video meeting link (Google Meet, Zoom, etc.)')),
                ('calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
