# Generated by Django 5.0.1 on 2026-01-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Available date')),
                ('start_time', models.TimeField(help_text='Start time for availability')),
                ('end_time', models.TimeField(help_text='End time for availability')),
                ('slot_duration', models.IntegerField(default=30, help_text='Duration of each slot in minutes (15, 30, or 60)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this availability is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availability',
                'ordering': ['-date', 'start_time'],
            },
        ),
    ]
