# Generated by Django 5.0.1 on 2026-01-08 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'role__in': ['admin', 'superadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('admin', 'date', 'start_time')},
        ),
    ]
